CREATE DATABASE NaciónBurgerDB;
GO

USE NaciónBurgerDB;
GO

CREATE TABLE Clientes (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DNI VARCHAR(8) NULL, -- 🔥 ahora permite NULL
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL UNIQUE
);

-- 🔥 índice único filtrado (correcto)
CREATE UNIQUE NONCLUSTERED INDEX IDX_Clientes_DNI_Filtered 
ON Clientes(DNI)
WHERE DNI IS NOT NULL;


CREATE TABLE Cargos (
    ID_CARGO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE Horarios (
    ID_HORARIO INT PRIMARY KEY IDENTITY(1,1),
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL
);

CREATE TABLE Trabajadores (
    ID_TRABAJADOR INT PRIMARY KEY IDENTITY(1,1),
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DNI VARCHAR(8) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL,
    ID_CARGO INT NOT NULL,
    ID_HORARIO INT NOT NULL,
    FOREIGN KEY (ID_CARGO) REFERENCES Cargos(ID_CARGO),
    FOREIGN KEY (ID_HORARIO) REFERENCES Horarios(ID_HORARIO)
);

-- ========================
-- USUARIOS (CORREGIDO)
-- ========================
CREATE TABLE Usuarios (
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    USUARIO VARCHAR(100) NOT NULL UNIQUE, -- 🔥 ampliado
    CONTRASENA VARCHAR(255) NULL, -- 🔥 ahora permite NULL
    GOOGLE_ID VARCHAR(255) NULL, -- 🔥 nuevo campo

    ID_CLIENTE INT NULL,
    ID_TRABAJADOR INT NULL,
    TIPO_USUARIO VARCHAR(20) NOT NULL DEFAULT 'cliente',

    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE),
    FOREIGN KEY (ID_TRABAJADOR) REFERENCES Trabajadores(ID_TRABAJADOR),

    CHECK (
        (ID_CLIENTE IS NOT NULL AND ID_TRABAJADOR IS NULL)
        OR
        (ID_CLIENTE IS NULL AND ID_TRABAJADOR IS NOT NULL)
    )
);

-- 🔥 índice único filtrado para GOOGLE_ID
CREATE UNIQUE NONCLUSTERED INDEX IDX_Usuarios_GOOGLE_ID
ON Usuarios(GOOGLE_ID)
WHERE GOOGLE_ID IS NOT NULL;

-- ========================
-- RESTO DE TABLAS (IGUALES)
-- ========================
CREATE TABLE Categoria_Productos (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(100) NOT NULL,
    CARPETA VARCHAR(100)
);

CREATE TABLE Estados_Producto (
    ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE Carta (
    ID_PLATILLO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    DESCRIPCION VARCHAR(255),
    IMAGEN VARCHAR(255),
    ID_CATEGORIA INT NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,

    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categoria_Productos(ID_CATEGORIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES Estados_Producto(ID_ESTADO)
);

CREATE TABLE Promociones (
    ID_PROMOCION INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(100),
    DESCUENTO DECIMAL(5,2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE Producto_Promocion (
    ID_PLATILLO INT,
    ID_PROMOCION INT,
    PRIMARY KEY (ID_PLATILLO, ID_PROMOCION),

    FOREIGN KEY (ID_PLATILLO) REFERENCES Carta(ID_PLATILLO),
    FOREIGN KEY (ID_PROMOCION) REFERENCES Promociones(ID_PROMOCION)
);

CREATE TABLE Estados_Mesa (
    ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE Mesas (
    ID_MESA INT PRIMARY KEY IDENTITY(1,1),
    NUMERO INT NOT NULL,
    ID_ESTADO INT,

    FOREIGN KEY (ID_ESTADO) REFERENCES Estados_Mesa(ID_ESTADO)
);

CREATE TABLE Estados_Pedido (
    ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE Tipos_Entrega (
    ID_TIPO_ENTREGA INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE Pedidos (
    ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
    FECHA_HORA DATETIME DEFAULT GETDATE(),

    ID_CLIENTE INT,
    ID_TRABAJADOR INT,
    ID_MESA INT,
    ID_ESTADO INT DEFAULT 1,
    ID_TIPO_ENTREGA INT,

    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE),
    FOREIGN KEY (ID_TRABAJADOR) REFERENCES Trabajadores(ID_TRABAJADOR),
    FOREIGN KEY (ID_MESA) REFERENCES Mesas(ID_MESA),

    FOREIGN KEY (ID_ESTADO) REFERENCES Estados_Pedido(ID_ESTADO),
    FOREIGN KEY (ID_TIPO_ENTREGA) REFERENCES Tipos_Entrega(ID_TIPO_ENTREGA)
);

CREATE TABLE Detalle_Pedidos (
    ID_DETALLE_PEDIDO INT PRIMARY KEY IDENTITY(1,1),

    ID_PEDIDO INT NOT NULL,
    ID_PLATILLO INT NOT NULL,

    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    DESCUENTO_APLICADO DECIMAL(5,2) DEFAULT 0,

    SUBTOTAL AS (CANTIDAD * (PRECIO_UNITARIO - DESCUENTO_APLICADO)) PERSISTED,
    IGV AS (CANTIDAD * (PRECIO_UNITARIO - DESCUENTO_APLICADO) * 0.18) PERSISTED,
    TOTAL AS (CANTIDAD * (PRECIO_UNITARIO - DESCUENTO_APLICADO) * 1.18) PERSISTED,

    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
    FOREIGN KEY (ID_PLATILLO) REFERENCES Carta(ID_PLATILLO)
);

CREATE TABLE Modalidades_Pago (
    ID_MODALIDAD INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE Estados_Pago (
    ID_ESTADO_PAGO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE Pagos (
    ID_PAGO INT PRIMARY KEY IDENTITY(1,1),

    ID_PEDIDO INT NOT NULL,
    ID_MODALIDAD INT NOT NULL,
    ID_ESTADO_PAGO INT DEFAULT 1,

    MONTO_TOTAL DECIMAL(10,2),
    FECHA_PAGO DATETIME NULL,
    NUMERO_PAGO INT,

    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
    FOREIGN KEY (ID_MODALIDAD) REFERENCES Modalidades_Pago(ID_MODALIDAD),
    FOREIGN KEY (ID_ESTADO_PAGO) REFERENCES Estados_Pago(ID_ESTADO_PAGO)
);

CREATE TABLE Comprobantes_Pago (
    ID_COMPROBANTE INT PRIMARY KEY IDENTITY(1,1),
    ID_PAGO INT,
    TIPO_COMPROBANTE VARCHAR(50),
    NUMERO_COMPROBANTE VARCHAR(50),

    FOREIGN KEY (ID_PAGO) REFERENCES Pagos(ID_PAGO)
);

CREATE TABLE Provincias (
    ID_PROVINCIA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100)
);

CREATE TABLE Distritos (
    ID_DISTRITO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    ID_PROVINCIA INT,

    FOREIGN KEY (ID_PROVINCIA) REFERENCES Provincias(ID_PROVINCIA)
);

CREATE TABLE Delivery (
    ID_ENVIO INT PRIMARY KEY IDENTITY(1,1),

    ID_PEDIDO INT,
    DIRECCION_ENTREGA VARCHAR(200),
    ESTADO_ENVIO VARCHAR(50),
    ID_DISTRITO INT,

    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
    FOREIGN KEY (ID_DISTRITO) REFERENCES Distritos(ID_DISTRITO)
);

CREATE TABLE Historial_Pedidos (
    ID_HISTORIAL INT PRIMARY KEY IDENTITY(1,1),

    ID_PEDIDO INT,
    ESTADO_ANTERIOR VARCHAR(50),
    ESTADO_NUEVO VARCHAR(50),

    FECHA_CAMBIO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO)
);

CREATE TABLE Devoluciones (
    ID_DEVOLUCION INT PRIMARY KEY IDENTITY(1,1),

    ID_PEDIDO INT,
    ID_PLATILLO INT,

    MONTO DECIMAL(10,2),
    MOTIVO VARCHAR(200),

    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
    FOREIGN KEY (ID_PLATILLO) REFERENCES Carta(ID_PLATILLO)
);

